### ISSUE TITLE
报错 Could not find Google Chrome executable

### ISSUE THREAD

**Issue by SammySnake-d** [LLM-Red-Team/metaso-free-api#35]
选用模式：简洁
搜索内容：ai科技
[2024-12-18 13:44:36.841][error][index<1044,28>] Error: Could not find Google Chrome executable for channel 'stable' at '/opt/google/chrome/chrome'.
    at computeSystemExecutablePath (file:///app/node_modules/@puppeteer/browsers/lib/esm/launch.js:34:15)
    at ChromeLauncher.executablePath (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:198:20)
    at ChromeLauncher.computeLaunchArguments (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:97:37)
    at ChromeLauncher.launch (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:39)
    at ChromeLauncher.launch (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:51:22)
    at PuppeteerNode.launch (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:129:31)
    at requestStream (file:///app/dist/index.js:1126:42)
    at file:///app/dist/index.js:1310:26
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /completions (file:///app/dist/index.js:1645:16)
[2024-12-18 13:44:36.841][info][index<995,30>] <- POST /hf/v1/chat/completions 23348ms

![image](https://github.com/user-attachments/assets/e73977a3-3959-43dd-80bd-eb36a6d9ef06)

**Comment by superZchen0701** [comment]
我也遇到这个问题，请问有解吗

**Comment by fiyen** [comment]
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && sudo apt-get update && sudo apt-get install -y google-chrome-stable
系统缺失一些模块，实测这个命令可以解决问题。
